# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Running tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry wheel
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libxxf86vm-dev libxfixes-dev libxi-dev libxkbcommon-dev libegl-dev
        poetry install --no-cache --no-root
    - name: Run tests
      run: |
        poetry run pytest
